// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package model

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ExecuteClient is the client API for Execute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecuteClient interface {
	LoL(ctx context.Context, in *ExecuteLoLRequest, opts ...grpc.CallOption) (*ExecuteLoLResponse, error)
	HistoryChan(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HistoryList, error)
}

type executeClient struct {
	cc grpc.ClientConnInterface
}

func NewExecuteClient(cc grpc.ClientConnInterface) ExecuteClient {
	return &executeClient{cc}
}

func (c *executeClient) LoL(ctx context.Context, in *ExecuteLoLRequest, opts ...grpc.CallOption) (*ExecuteLoLResponse, error) {
	out := new(ExecuteLoLResponse)
	err := c.cc.Invoke(ctx, "/boostlol.Execute/LoL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeClient) HistoryChan(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HistoryList, error) {
	out := new(HistoryList)
	err := c.cc.Invoke(ctx, "/boostlol.Execute/HistoryChan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecuteServer is the server API for Execute service.
// All implementations must embed UnimplementedExecuteServer
// for forward compatibility
type ExecuteServer interface {
	LoL(context.Context, *ExecuteLoLRequest) (*ExecuteLoLResponse, error)
	HistoryChan(context.Context, *emptypb.Empty) (*HistoryList, error)
	mustEmbedUnimplementedExecuteServer()
}

// UnimplementedExecuteServer must be embedded to have forward compatible implementations.
type UnimplementedExecuteServer struct {
}

func (UnimplementedExecuteServer) LoL(context.Context, *ExecuteLoLRequest) (*ExecuteLoLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoL not implemented")
}
func (UnimplementedExecuteServer) HistoryChan(context.Context, *emptypb.Empty) (*HistoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryChan not implemented")
}
func (UnimplementedExecuteServer) mustEmbedUnimplementedExecuteServer() {}

// UnsafeExecuteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecuteServer will
// result in compilation errors.
type UnsafeExecuteServer interface {
	mustEmbedUnimplementedExecuteServer()
}

func RegisterExecuteServer(s *grpc.Server, srv ExecuteServer) {
	s.RegisterService(&_Execute_serviceDesc, srv)
}

func _Execute_LoL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteLoLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteServer).LoL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Execute/LoL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteServer).LoL(ctx, req.(*ExecuteLoLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Execute_HistoryChan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteServer).HistoryChan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Execute/HistoryChan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteServer).HistoryChan(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Execute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boostlol.Execute",
	HandlerType: (*ExecuteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoL",
			Handler:    _Execute_LoL_Handler,
		},
		{
			MethodName: "HistoryChan",
			Handler:    _Execute_HistoryChan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lolconfig.proto",
}

// ConfigurationClient is the client API for Configuration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigurationClient interface {
	GetLiveConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Config, error)
}

type configurationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationClient(cc grpc.ClientConnInterface) ConfigurationClient {
	return &configurationClient{cc}
}

func (c *configurationClient) GetLiveConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/boostlol.Configuration/GetLiveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServer is the server API for Configuration service.
// All implementations must embed UnimplementedConfigurationServer
// for forward compatibility
type ConfigurationServer interface {
	GetLiveConfig(context.Context, *emptypb.Empty) (*Config, error)
	mustEmbedUnimplementedConfigurationServer()
}

// UnimplementedConfigurationServer must be embedded to have forward compatible implementations.
type UnimplementedConfigurationServer struct {
}

func (UnimplementedConfigurationServer) GetLiveConfig(context.Context, *emptypb.Empty) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveConfig not implemented")
}
func (UnimplementedConfigurationServer) mustEmbedUnimplementedConfigurationServer() {}

// UnsafeConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServer will
// result in compilation errors.
type UnsafeConfigurationServer interface {
	mustEmbedUnimplementedConfigurationServer()
}

func RegisterConfigurationServer(s *grpc.Server, srv ConfigurationServer) {
	s.RegisterService(&_Configuration_serviceDesc, srv)
}

func _Configuration_GetLiveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetLiveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Configuration/GetLiveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetLiveConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configuration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boostlol.Configuration",
	HandlerType: (*ConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLiveConfig",
			Handler:    _Configuration_GetLiveConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lolconfig.proto",
}

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	AuthWebhook(ctx context.Context, in *AuthWebhookRequest, opts ...grpc.CallOption) (*AuthWebhookResponse, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthWebhook(ctx context.Context, in *AuthWebhookRequest, opts ...grpc.CallOption) (*AuthWebhookResponse, error) {
	out := new(AuthWebhookResponse)
	err := c.cc.Invoke(ctx, "/boostlol.Auth/AuthWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	AuthWebhook(context.Context, *AuthWebhookRequest) (*AuthWebhookResponse, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) AuthWebhook(context.Context, *AuthWebhookRequest) (*AuthWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthWebhook not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AuthWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Auth/AuthWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthWebhook(ctx, req.(*AuthWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boostlol.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthWebhook",
			Handler:    _Auth_AuthWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lolconfig.proto",
}

// CommandsClient is the client API for Commands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandsClient interface {
	AddCommand(ctx context.Context, in *AddCommandRequest, opts ...grpc.CallOption) (*AddCommandResponse, error)
	DeleteCommand(ctx context.Context, in *DeleteCommandRequest, opts ...grpc.CallOption) (*DeleteCommandResponse, error)
	GetCommands(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCommandsResponse, error)
}

type commandsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandsClient(cc grpc.ClientConnInterface) CommandsClient {
	return &commandsClient{cc}
}

func (c *commandsClient) AddCommand(ctx context.Context, in *AddCommandRequest, opts ...grpc.CallOption) (*AddCommandResponse, error) {
	out := new(AddCommandResponse)
	err := c.cc.Invoke(ctx, "/boostlol.Commands/AddCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) DeleteCommand(ctx context.Context, in *DeleteCommandRequest, opts ...grpc.CallOption) (*DeleteCommandResponse, error) {
	out := new(DeleteCommandResponse)
	err := c.cc.Invoke(ctx, "/boostlol.Commands/DeleteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsClient) GetCommands(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCommandsResponse, error) {
	out := new(GetCommandsResponse)
	err := c.cc.Invoke(ctx, "/boostlol.Commands/GetCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandsServer is the server API for Commands service.
// All implementations must embed UnimplementedCommandsServer
// for forward compatibility
type CommandsServer interface {
	AddCommand(context.Context, *AddCommandRequest) (*AddCommandResponse, error)
	DeleteCommand(context.Context, *DeleteCommandRequest) (*DeleteCommandResponse, error)
	GetCommands(context.Context, *emptypb.Empty) (*GetCommandsResponse, error)
	mustEmbedUnimplementedCommandsServer()
}

// UnimplementedCommandsServer must be embedded to have forward compatible implementations.
type UnimplementedCommandsServer struct {
}

func (UnimplementedCommandsServer) AddCommand(context.Context, *AddCommandRequest) (*AddCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommand not implemented")
}
func (UnimplementedCommandsServer) DeleteCommand(context.Context, *DeleteCommandRequest) (*DeleteCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCommand not implemented")
}
func (UnimplementedCommandsServer) GetCommands(context.Context, *emptypb.Empty) (*GetCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommands not implemented")
}
func (UnimplementedCommandsServer) mustEmbedUnimplementedCommandsServer() {}

// UnsafeCommandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandsServer will
// result in compilation errors.
type UnsafeCommandsServer interface {
	mustEmbedUnimplementedCommandsServer()
}

func RegisterCommandsServer(s *grpc.Server, srv CommandsServer) {
	s.RegisterService(&_Commands_serviceDesc, srv)
}

func _Commands_AddCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).AddCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Commands/AddCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).AddCommand(ctx, req.(*AddCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_DeleteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).DeleteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Commands/DeleteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).DeleteCommand(ctx, req.(*DeleteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commands_GetCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).GetCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boostlol.Commands/GetCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).GetCommands(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commands_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boostlol.Commands",
	HandlerType: (*CommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCommand",
			Handler:    _Commands_AddCommand_Handler,
		},
		{
			MethodName: "DeleteCommand",
			Handler:    _Commands_DeleteCommand_Handler,
		},
		{
			MethodName: "GetCommands",
			Handler:    _Commands_GetCommands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lolconfig.proto",
}
